version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./public_html/:/var/www/html/
    container_name: php
    
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    ports:
      - "81:80"
    volumes:
      - ./public_html/:/var/www/html/
    container_name: apache
    
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    container_name: mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: 
        - mysql
    ports:
        - 82:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    container_name: myadmin
